// DO NOT EDIT THIS FILE !!!
import React from 'react'

interface IQuestion {
  question: string
  options:string[]
  answer: string
}

interface IQCMInterface {
  exerciseId: string
  exerciseTitle : string
  quiz: IQuestion[]
}

const QCM: Array<IQCMInterface> = [
  {
    exerciseId: 'src/exercise/01.md',
    exerciseTitle: 'Manipuler le DOM en JavaScript Natif',
    quiz: [
      {
        question: "Comment créer un élement DOM div en JavaScript ",
        options: ["window.createElement('div')", "document.createElement('div')", "document.createDiv()", "super.createElement('div')"],
        answer: "1"
      },{
        question: "Comment ajouter du texte sur cet élement ? (divEl)",
        options: ["divEl.text = 'le texte'", "divEl.setText = 'le texte'", "divEl.writeText = 'le texte'", "divEl.textContent = 'le texte'"],
        answer: "3"
      }
    ],
  },
  //export
  {
    exerciseId: 'src/exercise/02.md',
    exerciseTitle: 'Manipuler le DOM avec React',
    quiz: [
      {
        question: "Quel est l'équivalent de document.createElement('div') ?",
        options: ["ReactDOM.createElement('div')", "React.createElement('div')", "ReactJS.createElement('div')", "ReactRender.createElement('div')"],
        answer: "1"
      },{
        question: "Quel est l'équivalent de rootElement.append(element)",
        options: ["React.render(element, rootElement)", "ReactDOM.render(element, rootElement)", "ReactDOM.render(rootElement,element)", "React.render(rootElement,element)"],
        answer: "0"
      },{
        question: "React est ",
        options: ["Déclaration", "Impératif"],
        answer: "0"
      },{
        question: "Qu'est-ce que le prop children ?",
        options: ["Un prop comme un autre", "permet de gérer le CSS enfant", "permet l'imbrication de composants"],
        answer: "2"
      }
    ],
  },
  {
    exerciseId: 'src/exercise/03.md',
    exerciseTitle: 'Manipuler le style',
    quiz: [
      {
        question: "LEs styles  ?",
        options: ["css", "jss", "xss", "pdf"],
        answer: "0"
      },{
        question: "HMTL est ",
        options: ["a2", "b2", "c2", "d2"],
        answer: "2"
      } 
    ],
  },
]

//export default QCM;

const QcmComponent = () => {
  return (<>{ JSON.stringify(QCM, null, 2) }</>);
}
export default QcmComponent
