env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/strict
  - plugin:github/recommended
  - plugin:unicorn/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - github
  - json-format
  - unicorn
  - promise
rules:
  filenames/match-regex: off
  import/no-commonjs: off
  import/no-namespace: off
  unicorn/prevent-abbreviations: off
  unicorn/prefer-module: off
  unicorn/filename-case: off
  no-console: off
  no-unused-vars: off
  promise/always-return: error
  promise/no-return-wrap: error
  promise/param-names: error
  promise/catch-or-return: error
  promise/no-native: off
  promise/no-nesting: warn
  promise/no-promise-in-callback: warn
  promise/no-callback-in-promise: warn
  promise/no-new-statics: error
  promise/no-return-in-finally: warn
  promise/valid-params: warn
  promise/avoid-new: off
  react/prop-types: off
  unicorn/switch-case-braces: off
  eslint-comments/no-use: off
  jsx-a11y/alt-text: off
  @next/next/no-img-element: off
ignorePatterns:
  - src/**/*.js
